language: swift
before_install:
 - gem install xcpretty
osx_image: xcode9.4.1
script:
 - xcodebuild test -workspace ImageFilterWrapper.xcworkspace/ -scheme ImageFilterWrapperTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' | xcpretty -c && exit ${PIPESTATUS[0]}
